"""unique mans

Revision ID: d6eecaabb20c
Revises: 9229c19cc08c
Create Date: 2023-02-24 18:15:34.983977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6eecaabb20c'
down_revision = '9229c19cc08c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'updated_at')
    op.alter_column('manufacturers', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'manufacturers', ['name'])
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'manufacturers', type_='unique')
    op.alter_column('manufacturers', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('cars', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
